# The Default Profile
[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test= 'test/foundry'
cache-path='forge-cache'
solc_version = '0.8.15'
auto_detect_solc = false
optimizer_runs = 1_000

[fuzz]
runs = 1_000

# Extreme Fuzzing CI Profile :P
[profile.fuzz.ci]
runs = 100_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config